
# The name of your website.
name: Rapha Barreto

description: 

  # Description of your site. This will show up in google.
  meta: Esse é um simples blog criado para aprender e reunir informações do mundo da programação.

  # Description of your site. This will show up on the front page.
  subtitle: Esse é um simples blog criado para aprender e reunir informações do mundo da programação.

author:
  name: Rapha Barreto

  # Necessary for contact page
  email: tnt.raphael@gmail.com

  # Optional text (html) to display after author name. Leave empty if you don't
  # want it.
  info:

url: https://raphabarreto.com.br
baseurl: ""

# language attribute in <html> element.
lang: en

# FROM THIS POINT ON EVERYTHING IS OPTIONAL

##############
# APPEREANCE #
##############

# If you want to show the subtitle anywhere else than the front page, use
# {% include subtitle.html %} to include it anywhere you want.
show-subtitle: true
display-social-icons: true

# Preferably 64px in height. Leave empty = disable.
logo-image: # /img/logo.png

# Toolbar color for Chrome on Android.
theme-color-attr: "#00f0ff"

# Color of Microsoft live Tile.
ms-tile-color: "#00f0ff"

# Color used throughout the theme. Format: R, G, B.
theme-color: 0, 240, 255 # Original: 0, 240, 255

# Text color used throughout the theme. Format: R, G, B.
text-color: 0, 0, 0 # Original: 0, 0, 0

# Background color used throughout the theme. Format: R, G, B.
# Note: if you change the background color AND you use cover images, you should
#       also change the CSS gradient in "_includes\gradient.css" to match the
#       background color. Edit and copy it from here:
#       http://www.colorzilla.com/gradient-editor/#ffffff+0,ffffff+100&0+0,1+100
background-color: 255, 255, 255 # Original: 255, 255, 255

display-author-post-page: true
display-author-front-page: false

# http://alanwsmith.com/jekyll-liquid-date-formatting-examples
# date_format: "%b %-d, %Y"

# Minimal screen-width after which the navigation will change position from
# vertical to horizontal.
nav-breaking-point: 520px

# Number of posts on each page.
gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

# Display links for the previous and next post on post pages.
display-next-prev-post: true

# Leave empty if you don't want comments on post pages.
disqus-shortname: raphabarreto


################
# SOCIAL ICONS #
################

# Use a complete url here, including http:// and such. Requiring just usernames
# has been considered, but this is way more customizable.
twitter: https://twitter.com/RaphaelGuiba
youtube:
instagram:
tumblr:
facebook: https://www.facebook.com/raphaelguilherme.barreto
google-plus: https://plus.google.com/+RaphaelBarretoRGB
reddit:
soundcloud:
medium:
linkedin: https://br.linkedin.com/in/raphael-guilherme-barreto-15631747
github: https://github.com/raphabarreto
behance:
codepen:
dribbble:
trello:
stack-overflow:
bitcoin:
paypal:


#####################
# CUSTOMIZABLE TEXT #
#####################

# Useful for translating into other languages.

var_on_the_web: Redes Sociais
var_read: Ler # Text after each post summary on the homepage.
var_newer: Novo
var_older: Antigo
var_next_post: Próximo post
var_previous_post: Post anterior
var_less_than_a_minute_read: Menos de 1 min de leitura
var_min_read: min de leitura # Text after reading time. Example: 5 min read.
var_post_by: Post feito por
var_guest_post_by: Post convidado feito by
var_your_email: Seu email
var_your_message: Sua messagem


##################
# BUILD SETTINGS #
##################

# You don't have to change these.

exclude: [vendor]
highlighter: rouge
kramdown:
  input: GFM
paginate_path: "/page-:num/"
permalink: pretty
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      excerpt_separator: "<!--more-->"
